FROM ubuntu:14.04

#Always update your running system
RUN apt-get update -y

#You may or may not need to run these commands
RUN apt-get install -y wget
RUN apt-get install -y tar

RUN apt-get install -y build-essential #possibly need this to use the 'make' command
RUN apt-get install -y libssl-dev
RUN apt-get install -y make
RUN apt-get install -y libcurl4-gnutls-dev
RUN apt-get install -y libexpat1-dev
RUN apt-get install -y gettext
RUN apt-get install -y unzip

#for jenkins
RUN apt-get install -y yum

#### java ####
RUN mkdir /opt/jdk

WORKDIR /opt/jdk

RUN wget http://10.50.20.27:8080/aaron/downloads/jdk-8u45-linux-x64.tar.gz

RUN tar zxvf jdk-8u45-linux-x64.tar.gz

RUN update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_45/bin/java 2000

RUN update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_45/bin/javac 2000

ENV JAVA_HOME /opt/jdk/jdk1.8.0_45

ENV PATH $PATH:$JAVA_HOME/bin


### maven ###
RUN mkdir /opt/mvn

WORKDIR /opt/mvn

RUN wget http://10.50.20.27:8080/aaron/downloads/apache-maven-3.3.3-bin.tar.gz

RUN tar zxvf apache-maven-3.3.3-bin.tar.gz

RUN ln -s /opt/mvn/apache-maven-3.3.3 /bin/mvn

ENV MAVEN_HOME /opt/mvn/apache-maven-3.3.3

ENV PATH $PATH:$MAVEN_HOME/bin


### git ###
RUN mkdir /opt/git

WORKDIR /opt/git

RUN wget http://10.50.20.27:8080/aaron/downloads/git-2.5.0.tar.gz

RUN tar zxvf git-2.5.0.tar.gz

WORKDIR /opt/git/git-2.5.0

RUN sudo make prefix=/usr/local all && sudo prefix=/usr/local/install



### jenkins IS NOT WORKING !!! ###
WORKDIR /opt

RUN wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

RUN echo 'deb http://pkg.jenkins-ci.org/debian binary/' > /etc/apt/sources.list.d/jenkins.list

RUN apt-get update

RUN apt-get -y install jenkins

RUN service jenkins stop

RUN sed -i 's/8080/8083/g' /etc/default/jenkins

RUN service jenkins start









EXPOSE 8080

EXPOSE 8083

                 